### ISSUE TITLE
API: implement Species endpoint

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#17]
Mimic @cunzhig's implementations of `Person` and `Planet`.  Modify `serializers.py`, `views.py`, and `urls.py`.  Add at least two querystring key-value pairs to permit more refined search expressions.

**Comment by jadeharr** [comment]
I am working on finishing this issue on the pull request #27

**Comment by jadeharr** [comment]
This has been issue has been merged. I will close it now.
