### ISSUE TITLE
Model:  change table name to Vehicle; PK to vehicle_id

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#22]
Use singular tense for database entities (e.g., Film, Person, Planet, etc.).  PK needs to use singluar tense.

Model name: Vehicle

Change PK from
`vehicles_id = models.AutoField(primary_key=True)`
to
`vehicle_id = models.AutoField(primary_key=True)`

This will require a migration.

**Comment by garrisok** [comment]
Addressed in PR #34
