### ISSUE TITLE
Model: Change Starships class to Starship

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#23]
Use singular tense for database entities (e.g., Film, Person, Planet, etc.).  Primary key does not need to be updated.

Model/database table name: Starship

This will require a migration.

**Comment by garrisok** [comment]
Updated and ran local to confirm after migrations made

**Comment by garrisok** [comment]
Resolved with PR #24

**Comment by garrisok** [comment]
Resolved & merged.
