### ISSUE TITLE
Model: change field 'people' to 'characters' in Film class

### ISSUE THREAD

**Issue by cunzhig** [umsi-arwhyte/gffa#26]
The field `people` should be `characters` according to the documentation.
Things not sure about: the field is now `ForeignKey`. Should it be changed to "ManyToMany"?

**Comment by arwhyte** [comment]
Yes, change `people` to `characters`.  Films, Species, Starships, Vehicles fields should all be modeled as a M-M relationship.

**Comment by cunzhig** [comment]
Solved by #31
