### ISSUE TITLE
Include for loop within unordered list in html template files

### ISSUE THREAD

**Issue by jadeharr** [umsi-arwhyte/gffa#41]
At the moment the html template files for `planets`, `films`, `people`, `species`, `starships`, and `vehicles` have a for loop command outside of the unordered list (`<ul>`). This will have to be updated so that the for loop is within the unordered list.

Old example from `people.html`:
{% for item in starship %}
  `<ul>`
     <li>{{ item.name }}</li>
  `</ul>`
{% endfor %}

New example for 
`<ul>`
  {% for item in starship %}
     <li>{{ item.name }}</li>
  {% endfor %}
`</ul>`

This makes it so that we are not creating a new unordered list every time an item is listed.

**Comment by mdhamid1** [comment]
changed the location of for loop as per instructions.
