### ISSUE TITLE
Vehicle: create list and detail views, create vehicle_detail.html; update vehicle.html, add routes

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#46]
### Tasks:

1. `views.py`: create `VehicleDetailView()`. Mimic `PersonDetailView()`.
2. `urls.py`: add `VehicleDetailView` route.  Mimic `PersonDetailView
3. Templates: update `vehicles.html`.  Add link to `vehicle_detail.html` page.  Change `item` to `vehicle` (e.g., `for vehicle in vehicles`).  Mimic `people.html`. Adopt 4 spaces indenting.
4. Templates: create `vehicle_detail.html`.  Mimic `person_detail.html`. Adopt 4 spaces indenting rather than 2 spaces (will update person_detail.html indenting).

**Comment by JayLBrown** [comment]
Resolved - see #61
