### ISSUE TITLE
Film: create list and detail views, create Film_detail.html; update Film.html, add routes

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#47]
### Tasks

1. `views.py`: create `FilmDetailView()`. Mimic `PersonDetailView()`.
2. `urls.py`: add `FilmDetailView` route.  Mimic `PersonDetailView
3. Templates: update `films.html`.  Add link to `film_detail.html` page.  Adopt 4 spaces indenting.
4. Templates: create `film_detail.html`.  Mimic `person_detail.html`. Adopt 4 spaces indenting rather than 2 spaces (will update person_detail.html indenting).

**Comment by ykamat** [comment]
Resolved by #56
