### ISSUE TITLE
Documentation: remove reference to helper libraries

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#65]
Remove all references to helper libraries on the Documentation page.

### Text

Helper libraries
There are a bunch of helper libraries available for consuming the Star Wars API in a native programming language.

helper_library_gif

Python
swapi-python is built by the author of swapi, Paul Hallett.

Javascript
SWAPI-Wrapper By Raymond Camden.
swapi-node by Lucas Holmquist.

Android
SWAPI-Android-SDK by Julien Salvi.

Java
SWAPI by Maarten Dekker.

Go
swapi-go by Peter Hellberg.
swapi by Lee Jarvis.

PHP
Coruscant by DraperStudio.
swapi-php by Ross Masters.

Ruby
swapi-ruby by Ezequiel Maraschio.
Tatooine by Phil Nash.
swgem by Igor Souza.

C Sharp
SharpTrooper by Olcay Bayram.
SWapiCSharp by M-Yankov

Objective C
Falcon by Niels de Hoog.

Angular
xyz-angular-swapi by Matteo Ronchi.
ne-swapi by Nick Escallon.

Angular 2
ng2-swapi by Gianmaria Leoni.

R
rwars by Oliver Keyes.

F#
fsharp-swapi by Evelina Gabasova.

Elixir
swapi.ex by Tim Whitacre.
ex_swapi by Mark Chavez.
elixir-swapi by Kyle Surowiec.

**Comment by jadeharr** [comment]
This issue was completed in PR #66
