### ISSUE TITLE
Species: add, update, delete web forms

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#75]
Implement add, update and delete templates, supporting routes (`urls.py`), backing form class in `forms.py`, and view classes.

< Entity > = object name  placeholder

### `forms.py`

```python
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from . models import < Entity >


class <Entity>Form(forms.ModelForm):
         """ Docstring TODO"""

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'POST'
		self.helper.add_input(Submit('submit', 'Submit'))

	class Meta:
		model = < Entity >
		fields = '__all__'
```

### `urls.py`

```python
urlpatterns = [
	. . .
	path('< entity >/new/', views.< Entity >CreateView.as_view(), name='< entity >_new'),
	path('< entity >/<int:pk>/', views.< Entity >DetailView.as_view(), name='< entity >_detail'),
	path('< entity >/<int:pk>/delete/', views.< Entity >DeleteView.as_view(), name='< entity >_delete'),
	path('< entity >/<int:pk>/update/', views.< Entity >UpdateView.as_view(), name='< entity >_update'),
]
```

### `views.py`

For code examples of form-related View classes see 

https://github.com/umsi-arwhyte/heritagesites/blob/master/heritagesites/views.py

particularly:

* `SiteCreateView(generic.View)`
* `SiteDeleteView(generic.DeleteView)`
* `SiteUpdateView(generic.UpdateView)`

Note use of the class decorators:

```python
@method_decorator(login_required, name='dispatch')
```

**Comment by arwhyte** [comment]
Reassigned to @ykamat.

**Comment by mdhamid1** [comment]
@arwhyte for the implementation of the species form I am adding a field to allow selection of which characters are of the species being created in form. To accomplish this, I will be creating a through table model I'm calling SpeciesCharacter. Do you approve tracking which characters are of the species being created? Or would you prefer I do something else, like which films the species appeared in?
