### ISSUE TITLE
Contributors: add page

### ISSUE THREAD

**Issue by arwhyte** [umsi-arwhyte/gffa#83]
Add Contributors page listing all contributors found here: https://github.com/umsi-arwhyte/gffa/graphs/contributors.  Make it the 4th item on the top bar menu. Consider styling similar to team page at https://www.si506.org/team/.  However, don't include contact details other than Github handles (use follow me buttons like the arwhyte ones on the home page).  Also list me last.  Students first. 

For university affiliations see mcommunity: https://mcommunity.umich.edu/

### Contributors

Jade Harrison, [UMSI MADS](https://mads.si.umich.edu/?gclid=CjwKCAjwgZuDBhBTEiwAXNofRH3dk2L4S2Fy2bE-WVqosqMoUA9jXSHFSr8tDX5u1D9Afs4B0wpxaxoCPCIQAvD_BwE) program  ([@jadeharr](https://github.com/jadeharr))
...
Yash Kammat, [UMSI MSI](https://www.si.umich.edu/programs/master-science-information) program ([@ykamat](https://github.com/ykamat))
...
Anthony Whyte, [UMSI Lecturer](https://www.si.umich.edu/people/anthony-whyte) ([@arwhyte](https://github.com/arwhyte))

**Comment by jadeharr** [comment]
This issue was completed in PR #87
