### ISSUE TITLE
Spreadsheet for new characters, films, etc. on Wookiepedia

### ISSUE THREAD

**Issue by jadeharr** [umsi-arwhyte/gffa#89]
There have been a few new movies and shows that have come out since SWAPI has last been updated. These films, characters, etc. need to be updated to out own database. To do this, we will need to amass this new information and an easy way to do this is to split the work between us. We can  each take a film or an entity and input the data we get into a spreadsheet.

**Comment by mdhamid1** [comment]
I can start looking into this. Will give you guys an update with where I am on this in our next meeting.
